sonar.projectKey=Muhammad Faizan
sonar.organization=mfaizan20

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/target/**,**/coverage/**

sonar.sourceEncoding=UTF-8
